---
title: "ShopifyGet"
author: Matt Boone
output: 
  html_document:
      code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This markdown file extracts table data from the Shopify

```{r Shopify Setup echo = FALSE}
#https://www.gormanalysis.com/blog/pulling-shopify-data-into-r-with-shopr/
#install.packages("devtools")
#devtools::install_github("ben519/shopr")

#install.packages("tidyverse")
#install.packages("openxlsx")
#install.packages("fuzzyjoin")
#install.packages("data.table")

library(dplyr)
library(openxlsx)
library(tidyverse)
library(shopr)
library(fuzzyjoin)
library(data.table)

#may not use below packages
#install.packages("googlesheets4")
#library(googlesheets4)

#install.packages("googledrive")
#library(googledrive)
```


```{r get days between dates, echo=FALSE}
#pull api keys into environment
#requires separate .r file titled `storeget_keys.r` to be saved with api keys for store url, api key, and api password.
source('storeget_keys.r')

#determine how far back to pull data in days

shopstartdate <- as.Date("2018-06-01")
today <- Sys.Date()

today-shopstartdate

#assign look-back quantity of days
days <- 2
```


```{r get order data, echo=FALSE}

#pull from shopify
orders_0 <- shopr_get_orders(
  shopURL = "sho-_store_url", 
  APIKey = "shop_API_Key", 
  APIPassword = "shop_API_Pass",
  created_at_min = Sys.time() - 60*60*24*days,
  created_at_max = NULL
)

orders <- orders_0$orders
discount_applications <- orders_0$discount_applications
discount_codes  <- orders_0$discount_codes
tax_lines <- orders_0$tax_lines
line_items <- orders_0$line_items
fulfillments <- orders_0$fulfillments
refunds <- orders_0$refunds
shipping_lines <- orders_0$shipping_lines

filelocation <- "C:/Users/Matthew Boone/Desktop/OPSEC/DataDownloads/"fa
filename_0 <- paste("ordersx ","(",days," days) ",format(Sys.time(),"%Y-%b-%d"),".xlsx", sep="")
filename <- paste(filelocation,filename_0,sep = "")

write.xlsx(
  orders_0,
  filename, 
  sheetName = "Orders",
  row.names = FALSE,
  showNA = TRUE,
  password = NULL
  )
```

```{r table cleanup}
orders <- rename(orders,
                   order_id = id,
                   ordercreatedate = created_at,
                   )

line_items <- rename(line_items,
                   lineitem_id = id,
                   lineitem_name = name,
                   msrp = price 
                   )
fulfillments <- rename(fulfillments,
                         fulfilleddate = updated_at
                         )


```


```{r cleanup of orders file}
#merge product line item details into orders
detail_0 <- left_join(select(orders,"order_id","name","ordercreatedate","email","note","total_line_items_price","subtotal_price","total_tax","taxes_included","financial_status","total_discounts","shipping_address.country_code","shipping_address.province_code","customer.id","customer.tax_exempt"
),select(line_items,"lineitem_id","variant_id","quantity","sku","lineitem_name","msrp","order_id"), by = c("order_id"), keep = FALSE)

#merge discount details into detail_0
detail_1 <- detail_0 %>%
  left_join(select(discount_codes,"code","order_id"),by = c("order_id"))

#merge fulfillment details into detail_1
ordersdetail <- detail_1 %>%
  left_join(select(fulfillments_0,"fulfilleddate","order_id"),by = c("order_id"))

#save as .xlsx file to desired folder
filelocation <- "C:/Users/Matthew Boone/Desktop/OPSEC/DataDownloads/"
filename_0 <- paste("ordersdetail ","(",days," days) ",format(Sys.time(),"%y-%m-%d"),".xlsx", sep="")
filename <- paste(filelocation,filename_0,sep = "")

write.xlsx(
  ordersdetail,
  filename, 
  sheetName = "Orders",
  row.names = FALSE,
  showNA = TRUE,
  password = NULL
)
```


```{r run code to here}

```

```{r get and manage products}
products_0 <- shopr_get_products(
  shopURL = shop_store_url,
  APIKey = shop_API_Key, 
  APIPassword = shop_API_Pass)
products <- products_0$products
pvariants <- products_0$variants
products <- rename(products,
                   product_id = id
                   )
pvariants <- rename(pvariants,
                    variant_id = id,
                    variant_title = title,
                    msrp = price)
products_1 <- left_join(select(products,"product_id","title","product_type"),
                        select(pvariants,"sku","msrp","option1","product_id"),
                        by = c("product_id"), keep = FALSE)
```


